TARGET = a b c d e ff ex
CC = g++
INCLUDE = -I./include
CFLAGS = -g -Wall -O2 -std=c++17 $(INCDIR)

.cpp:
	$(CC) $(CFLAGS) -o $@ $<

# .PHONY : clean

# clean:
# 	rm -rf *.a *.o *~ $(TARGET)
#     echo "clean"
